on: push
name: Tests

jobs:
  onMasterOrPR:
    name: On master or PR
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Dependencies
      run: make ensure
    - name: Lint
      run: make fmt
    - name: Test
      run: make test
    - name: Cover
      run: make cover

  deploy:
    name: Deploy to WP.org
    steps:
      - uses: actions/bin/filter@master"
      - name: New Tag
        args: tag
      - uses: ./.github/deploy
        env:
          SLUG: spiderblocker
        with:
          username: ${{ secrets.SVN_USERNAME }}
          password: ${{ secrets.SVN_PASSWORD }}
